express_table = {2: "示爱",
                 4: "得意",
                 5: "流泪",
                 8: "睡",
                 9: "大哭",
                 10: "尴尬",
                 12: "调皮",
                 14: "微笑",
                 16: "酷",
                 21: "可爱",
                 23: "傲慢",
                 24: "饥饿",
                 25: "困",
                 26: "惊恐",
                 27: "流汗",
                 28: "憨笑",
                 29: "悠闲",
                 30: "奋斗",
                 32: "疑问",
                 33: "嘘",
                 34: "晕",
                 38: "敲打",
                 39: "再见",
                 41: "发抖",
                 42: "爱情",
                 43: "跳跳",
                 49: "拥抱",
                 53: "蛋糕",
                 60: "咖啡",
                 63: "玫瑰",
                 66: "爱心",
                 74: "太阳",
                 75: "月亮",
                 76: "赞",
                 78: "握手",
                 79: "胜利",
                 85: "飞吻",
                 89: "西瓜",
                 96: "冷汗",
                 97: "擦汗",
                 98: "抠鼻",
                 99: "鼓掌",
                 100: "糗大了",
                 101: "坏笑",
                 102: "左哼哼",
                 103: "右哼哼",
                 104: "哈欠",
                 106: "委屈",
                 109: "左亲亲",
                 111: "可怜",
                 116: "示爱",
                 118: "抱拳",
                 120: "拳头",
                 122: "爱你",
                 123: "NO",
                 124: "OK",
                 125: "转圈",
                 129: "挥手",
                 144: "喝彩",
                 147: "棒棒糖",
                 171: "茶",
                 173: "泪奔",
                 174: "无奈",
                 175: "卖萌",
                 176: "小纠结",
                 179: "doge",
                 180: "惊喜",
                 181: "骚扰",
                 182: "笑哭",
                 183: "我最美",
                 201: "点赞",
                 203: "托脸",
                 212: "托腮",
                 214: "啵啵",
                 219: "蹭一蹭",
                 222: "抱抱",
                 227: "拍手",
                 232: "佛系",
                 240: "喷脸",
                 243: "甩头",
                 246: "加油抱抱",
                 262: "脑阔疼",
                 264: "捂脸",
                 265: "辣眼睛",
                 266: "哦哟",
                 267: "头秃",
                 268: "问号脸",
                 269: "暗中观察",
                 270: "emm",
                 271: "吃瓜",
                 272: "呵呵哒",
                 273: "我酸了",
                 277: "汪汪",
                 278: "汗",
                 281: "无眼笑",
                 282: "敬礼",
                 284: "面无表情",
                 285: "摸鱼",
                 287: "哦",
                 289: "睁眼",
                 290: "敲开心",
                 293: "摸锦鲤",
                 294: "期待",
                 297: "拜谢",
                 298: "元宝",
                 299: "牛啊",
                 305: "右亲亲",
                 306: "牛气冲天",
                 307: "喵喵",
                 314: "仔细分析",
                 315: "加油",
                 318: "崇拜",
                 319: "比心",
                 320: "庆祝",
                 322: "拒绝",
                 324: "吃糖",
                 326: "生气",
                 9728: "☀ 晴天",
                 9749: "☕ 咖啡",
                 9786: "☺ 可爱",
                 10024: "✨ 闪光",
                 10060: "❌ 错误",
                 10068: "❔ 问号",
                 127801: "🌹 玫瑰",
                 127817: "🍉 西瓜",
                 127822: "🍎 苹果",
                 127827: "🍓 草莓",
                 127836: "🍜 拉面",
                 127838: "🍞 面包",
                 127847: "🍧 刨冰",
                 127866: "🍺 啤酒",
                 127867: "🍻 干杯",
                 127881: "🎉 庆祝",
                 128027: "🐛 虫",
                 128046: "🐮 牛",
                 128051: "🐳 鲸鱼",
                 128053: "🐵 猴",
                 128074: "👊 拳头",
                 128076: "👌 好的",
                 128077: "👍 厉害",
                 128079: "👏 鼓掌",
                 128089: "👙 内衣",
                 128102: "👦 男孩",
                 128104: "👨 爸爸",
                 128147: "💓 爱心",
                 128157: "💝 礼物",
                 128164: "💤 睡觉",
                 128166: "💦 水",
                 128168: "💨 吹气",
                 128170: "💪 肌肉",
                 128235: "📫 邮箱",
                 128293: "🔥 火",
                 128513: "😁 呲牙",
                 128514: "😂 激动",
                 128516: "😄 高兴",
                 128522: "😊 嘿嘿",
                 128524: "😌 羞涩",
                 128527: "😏 哼哼",
                 128530: "😒 不屑",
                 128531: "😓 汗",
                 128532: "😔 失落",
                 128536: "😘 飞吻",
                 128538: "😚 亲亲",
                 128540: "😜 淘气",
                 128541: "😝 吐舌",
                 128557: "😭 大哭",
                 128560: "😰 紧张",
                 128563: "😳 瞪眼"
                 }

express_summon_data_for_old = {
    "data": [
        "task(000000000000000)",
        "masterpiece,(bestquality),highlydetailed,ultra-detailed,cute,solo,(1catgirl),(detailedeyes),(shineblueeyes),(longhair:1.2),(white hair:1.2),(fluffyhair),(catears),smallnose,(pinknose),(whiskers),(longsleeves),(puffysleeves),(frillydress),(cat tail:1.2),(1tail:1.5),fluffytail,(pawboots),(softlighting),(pastelcolors),(gentleexpression),(innocentlook),white background,(upper_body:1.5),",
        "logo,text,blurry,low quality,bad anatomy,sketches,lowres,normal quality,monochrome,username,out of focus,bad proportions,cropped,watermark,signature,worstquality,grayscale,Multiple people,mutated,mutation,ugly,disfigured,poorly drawn face,skin blemishes,skin spots,deformed,long neck,(fat:1.2),long body,bad body,missing limb,malformed limbs,disconnected limbs,floating limbs,extra limb,extra arms,mutated hands,fused fingers,missing fingers,malformed hands,bad hands,too many fingers,mutated hands and fingers,extra legs,bad feet,poorly drawn hands,hand_over_hand,crossed_hand,",
        [],
        1,
        1,
        7,
        3.5,
        270,
        256,
        False,
        0.7,
        2,
        "Latent",
        0,
        0,
        0,
        "Use same checkpoint",
        [
            "Use same choices"
        ],
        "Use same sampler",
        "Use same scheduler",
        "",
        "",
        7,
        3.5,
        None,
        "None",
        20,
        "Euler a",
        "Automatic",
        False,
        "",
        0.8,
        -1,
        False,
        -1,
        0,
        0,
        0,
        True,
        False,
        None,
        None,
        None,
        None,
        False,
        "(SDXL) Only Generate Transparent Image (Attention Injection)",
        1,
        1,
        "",
        "",
        "",
        "Crop and Resize",
        False,
        "",
        "",
        "",
        None,
        None,
        None,
        False,
        7,
        1,
        "Constant",
        0,
        "Constant",
        0,
        1,
        "enable",
        "MEAN",
        "AD",
        1,
        False,
        1.01,
        1.02,
        0.99,
        0.95,
        0,
        1,
        False,
        0.5,
        2,
        1,
        False,
        3,
        False,
        3,
        2,
        0,
        0.35,
        True,
        "bicubic",
        "bicubic",
        False,
        0,
        "anisotropic",
        0,
        "reinhard",
        100,
        0,
        "subtract",
        0,
        0,
        "gaussian",
        "add",
        0,
        100,
        127,
        0,
        "hard_clamp",
        5,
        0,
        "None",
        "None",
        False,
        "MultiDiffusion",
        768,
        768,
        64,
        4,
        False,
        1,
        False,
        False,
        False,
        False,
        "positive",
        "comma",
        0,
        False,
        False,
        "start",
        "",
        "Seed",
        "",
        "",
        "Nothing",
        "",
        "",
        "Nothing",
        "",
        "",
        True,
        False,
        False,
        False,
        False,
        False,
        False,
        0,
        False
    ],
    "event_data": None,
    "fn_index": 496,
    "trigger_id": 16,
    "session_hash": "nhtugpn3ekc"
}

express_summon_data = {
    "prompt": "masterpiece,(bestquality),highlydetailed,ultra-detailed,cute,solo,(1catgirl),(detailedeyes),"
              "(shineblueeyes),(longhair:1.2),(white hair:1.2),(fluffyhair),(catears),smallnose,(pinknose),"
              "(whiskers),(longsleeves),(puffysleeves),(frillydress),(cat tail:1.2),(1tail:1.5),fluffytail,"
              "(pawboots),(softlighting),(pastelcolors),(gentleexpression),(innocentlook),white background,"
              "(upper_body:1.5),",
    "negative_prompt": "logo,text,blurry,low quality,bad anatomy,sketches,lowres,normal quality,monochrome,username,"
                       "out of focus,bad proportions,cropped,watermark,signature,worstquality,grayscale,"
                       "Multiple people,mutated,mutation,ugly,disfigured,poorly drawn face,skin blemishes,skin spots,"
                       "deformed,long neck,(fat:1.2),long body,bad body,missing limb,malformed limbs,disconnected "
                       "limbs,floating limbs,extra limb,extra arms,mutated hands,fused fingers,missing fingers,"
                       "malformed hands,bad hands,too many fingers,mutated hands and fingers,extra legs,bad feet,"
                       "poorly drawn hands,hand_over_hand,crossed_hand,",
    "steps": 20,
    "sampler_name": "DPM++ 2M Karras",
    "width": 256,
    "height": 270,
    "save_image": True,
    "override_settings": {
        "sd_model_checkpoint": "极光5.1.fp16.safetensors"  # 指定模型
    }
}
